### PR TITLE
Added video

### PR DESCRIPTION
**Pull request by rsiemens**
Added Philip Guo's CPython internals walkthrough video series.

### CODE REVIEW

**Comment by s16h** [comment]
Thanks for the pull request. I need a bit of time going through all of these videos before I merge. So far it's awesome. Thanks again.

**Comment by s16h** [comment]
These are awesome - must-watch. They are my personal favourite videos of the year. I just need to figure how we should represent multi-part videos in the JSON before I add this. Sorry for the delay.

**Comment by Nudies** [comment]
:+1:

**Comment by s16h** [comment]
Still haven't had a chance to sort out multi-part videos :(

**Comment by htlcnn** [comment]
Maybe add them to a playlist and post the playlist link

**Comment by s16h** [comment]
Excellent idea. Still need to figure out what the website would show; will have a go at it this weekend.

**Pull request closed without merging**
