### PR TITLE
Super considered Super - Raymond Hettinger

### PR DESCRIPTION
**Pull request by ssundarraj**
[Review on Reviewable](https://reviewable.io/reviews/s16h/py-must-watch/59)

### CODE REVIEW

**Comment by SylvainDe** [comment]
Hi,
Thanks for the link. IMHO, it could be a good idea to add links to Presentation https://us.pycon.org/2015/schedule/presentation/419/ and to the article https://rhettinger.wordpress.com/2011/05/26/super-considered-super/ .

**Comment by bittner** [comment]
:+1:

**Comment by s16h** [comment]
@ssundarraj, do you want to add the links to presentation and blog post as well? Then I can merge.

**Comment by ssundarraj** [comment]
Yeah. I'll add the links and make a push.

**Comment by ssundarraj** [comment]
@s16h  Done

**Comment by s16h** [comment]
Awesome; thank you. Just another quick request: could you also add it to the readme. This will soon be an unnecessary step as @SylvainDe has kindly written a script to take care of it but we have to manually do it for now.

**Comment by s16h** [comment]
Conflict needs to be resolved. :)

**Comment by ssundarraj** [comment]
Fixed!

**Comment by s16h** [comment]
Perfect.

**Pull request merged**
