### PR TITLE
Changing .gitignore and adding favicon

### PR DESCRIPTION
**Pull request by danjford**
- Adding favicon to the page for issue https://github.com/s16h/py-must-watch/issues/41

image

- Creating .gitignore and adding .DS_STORE to it

### CODE REVIEW

**Comment by danjford** [comment]
If you want to use the icon for anything other than a favicon (.ico) let me know and I'll export it as a different format as well

**Comment by s16h** [comment]
This is great, thanks. I think `.DS_STORE` is something that should be in one's global ignore file as opposed the the project-specific one. So, I'll remove that for now. Thanks.

**Comment by danjford** [comment]
@s16h have removed the .gitignore

**Comment by s16h** [comment]
Sweet.

**Pull request merged**
