### PR TITLE
Add 'Python Concurrency From the Ground Up - Live' by David Beazley

### PR DESCRIPTION
**Pull request by brouberol**
Every video from David Beazley is a must watch anyway :)

### CODE REVIEW

**Comment by adrianmoisey** [comment]
Dupe of https://github.com/s16h/py-must-watch/pull/50

**Comment by adrianmoisey** [comment]
Oh, not a dupe. But the same video.

**Comment by brouberol** [comment]
Oh right. I didn't see on the website, but didn't think about checking the open PRs. Sorry.

**Comment by brouberol** [comment]
Although, #50 added it to README.md, and I added it to videos.json. Merging both would not create a duplicate, would it?

**Comment by adrianmoisey** [comment]
No. This is still relevant, I think.

**Comment by brouberol** [comment]
Right, so I'll go and reopen this one.

**Comment by s16h** [comment]
I'll watch and add this in a few hours. Thanks a lot!

**Comment by brouberol** [comment]
You're welcome. That was the video of the year for me. Enjoy!

**Pull request merged**
